[package]
name = "wrappers"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[features]
default = ["pg14"]
pg10 = ["pgx/pg10", "pgx-tests/pg10" ]
pg11 = ["pgx/pg11", "pgx-tests/pg11" ]
pg12 = ["pgx/pg12", "pgx-tests/pg12" ]
pg13 = ["pgx/pg13", "pgx-tests/pg13" ]
pg14 = ["pgx/pg14", "pgx-tests/pg14" ]
pg_test = []

helloworld_fdw = []
bigquery_fdw = ["gcp-bigquery-client", "time", "serde_json"]
clickhouse_fdw = ["clickhouse-rs", "chrono", "time"]
stripe_fdw = ["reqwest", "reqwest-middleware", "reqwest-retry", "serde_json"]
firebase_fdw = ["reqwest", "reqwest-middleware", "reqwest-retry", "serde_json", "yup-oauth2", "regex", "time"]

[dependencies]
pgx = "=0.5.6"
cfg-if = "1.0"
#supabase-wrappers = "0.1"
supabase-wrappers = { path = "../supabase-wrappers" }

# for clickhouse_fdw
clickhouse-rs = { git = "https://github.com/suharev7/clickhouse-rs", branch = "async-await", features = ["tls"], optional = true }
chrono = { version = "0.4", optional = true }

# for bigquery_fdw, firebase_fdw and etc.
gcp-bigquery-client = { version = "0.16.0", optional = true }
time = { version = "0.3.15", features = ["parsing"], optional = true }

# for stripe_fdw, firebase_fdw and etc.
reqwest = { version = "0.11.12", features = ["json"], optional = true }
reqwest-middleware = { version = "0.1.6", optional = true }
reqwest-retry = { version = "0.1.5", optional = true }
serde_json = { version = "1.0.86", optional = true }

# for firebase_fdw
yup-oauth2 = { version = "8.0.0", optional = true }
regex = { version = "1", optional = true }

[dev-dependencies]
pgx-tests = "=0.5.6"

[profile.dev]
panic = "unwind"
lto = "thin"

[profile.release]
panic = "unwind"
opt-level = 3
lto = "fat"
codegen-units = 1
