version: '3'
services:

  test-wrappers:
    container_name: pg-wrappers
    build:
        context: ../..
        dockerfile: ./wrappers/dockerfiles/pg/Dockerfile
    command:
      - ./bin/installcheck
