version: '3'
services:
  test-wrappers:
    container_name: pg-wrappers
    build:
        context: ../..
         dockerfile: ./wrappers/dockerfiles/pg/Dockerfile
     command:
       - ./bin/installcheck
     depends_on:
       clickhouse:
         condition: service_healthy
       stripe:
         condition: service_healthy


   clickhouse:
     image: clickhouse/clickhouse-server
     container_name: clickhouse-wrapped
     volumes:
         - ../dockerfiles/clickhouse/setup.sql:/docker-entrypoint-initdb.d/setup.sql
     environment:
       CLICKHOUSE_DB: supa
     ports:
       - "9000:9000" # native interface
       - "8123:8123" # http interface
     healthcheck:
       test: sleep 4 && wget --no-verbose --tries=1 --spider http://localhost:8123/?query=SELECT%201 || exit 1
       interval: 30s
       timeout: 5s
       retries: 3
   stripe:
     image: stripe/stripe-mock:v0.144.0
     container_name: stripe-mock
     volumes:
         - ../dockerfiles/stripe/setup.sql:/docker-entrypoint-initdb.d/setup.sql
     ports:
       - "12111-12112:12111-12112"
     healthcheck:
       test: sleep 4 && wget --no-verbose --tries=1 --spider http://localhost:12111/ || exit 1
       interval: 10s
       timeout: 5s
       retries: 30
