version: '3'
services:

  test-wrappers:
    container_name: pg-wrappers
    build:
        context: ../..
        dockerfile: ./wrappers/dockerfiles/pg/Dockerfile
    volumes:
        - ../results:/home/app/wrappers/results
    command:
      - ./bin/installcheck
    depends_on:
      clickhouse:
        condition: service_healthy
      firebase:
        condition: service_healthy

  clickhouse:
    image: clickhouse/clickhouse-server
    container_name: clickhouse-wrapped
    volumes:
        - ../dockerfiles/clickhouse/setup.sql:/docker-entrypoint-initdb.d/setup.sql
    environment:
      CLICKHOUSE_DB: supa
    ports:
      - "9000:9000" # native interface
      - "8123:8123" # http interface
    healthcheck:
      test: sleep 4 && wget --no-verbose --tries=1 --spider http://localhost:8123/?query=SELECT%201 || exit 1
      interval: 10s
      timeout: 5s
      retries: 20

  firebase:
    image: andreysenov/firebase-tools
    container_name: firebase-wrapped
    command: firebase emulators:start --project supa --import=./baseline-data
    volumes:
        - ../dockerfiles/firebase:/home/node
    ports:
      - "4000:4000" # UI
      - "8080:8080" # Firestore
      - "9099:9099" # Auth
    healthcheck:
      test: sleep 4 && wget --no-verbose --tries=1 --spider http://localhost:9099/ || exit 1
      interval: 10s
      timeout: 5s
      retries: 30
